services:
  # MySQL service
  mysql:
    image: mysql:8.4.8
    container_name: mysql
    hostname: ${MYSQL_HOSTNAME}
    env_file:
     - .env.dev
    environment:
      MYSQL_DATABASE: ${MYSQL_CORE_DATABASE}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      LANG: C.UTF-8
      LC_ALL: C.UTF-8
      TZ: Europe/Prague
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - mysql_data:/var/lib/mysql
      - ./Docker/mysql:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "${MYSQL_ROOT_USER}", "-p${MYSQL_ROOT_PASSWORD}"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

  # Backend service (Django)
  backend:
    build:
      context: .
      dockerfile: Docker/backend/DockerFile.dev
    container_name: backend
    ports:
      - "8000:8000"
    env_file:
      - .env.dev
    volumes:
      - ./Backend:/decinkanext
      - ./djangocache:/tmp/django_cache
      - ./logs:/decinkanext/logs
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - mynetwork
    healthcheck:
      test: ["CMD", "python", "manage.py", "check"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 60s

# Networks definition
# This section defines the custom network used by the services
networks:
  mynetwork:
    driver: bridge

# Volumes definition
# This section defines the named volumes used by the services
volumes:
  mysql_data: